---
abstract: 'Reload %INC files when updated on disk'
author:
  - 'Joshua Pritikin <jprit@cpan.org>'
  - 'Doug MacEachern <dougm@cpan.org>'
build_requires:
  Test: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Module-Reload
requires:
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilbowers/Module-Reload
  repository: https://github.com/neilbowers/Module-Reload.git
version: '1.08'
